# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ This file is read only once per server start. Restart server when changed! ║
# ╚════════════════════════════════════════════════════════════════════════════╝

title: Bothle
email: wambeke7@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Crowdfunding website for Bothle
  A bottle with two compartiments that you can choose the tempature for each compartiment
baseurl: "/1819-crowdfunding-arnewamb" # the subpath of your site, e.g. /blog
url: "https://gdmgent-1819-nmd2.github.io/1819-crowdfunding-arnewamb/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  gdm-1718-arnewamb

# Build settings


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
plugins:
# - jekyll-feed
# - jekyll-gist
# - jekyll-mentions
# - jekyll-paginate
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-sitemap
 # - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - config.codekit3
  - README.md
